---
# yamllint disable rule:line-length
name: Build and tests

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10.11", "3.11.5", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest coverage setuptools
          pip install -e "."
      - name: install cmake
        run: |
          sudo apt-get -y install cmake
      - name: build with cmake
        run: |
          pwd
          git submodule
          git submodule init
          git submodule sync
          git submodule update
          cmake .
          cmake --build .
          sudo cmake --install .
          sudo chown -R $(id -u -n) /var/log/munin-node
          find |grep munin-node-python$
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=16 --max-line-length=127 --statistics
      - name: Try to setup.py
        run: |
          pip install -e "."
          python setup.py install
      - name: Run munin-node-configure
        run: |
          munin-node-configure
          munin-node-configure --shell
          munin-node-configure --suggest
          munin-node-configure --shell --suggest
      - name: Try to run munin-node
        run: |
          find /opt|grep munin
          cat /opt/hostedtoolcache/Python/*/x64/bin/munin-node-python
          munin-node-python
